# Generated by Django 6.0 on 2026-01-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_adminprofile_student_tag_teacher_category_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_date',
        ),
    ]
