# Generated by Django 6.0 on 2026-01-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_active_remove_category_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, help_text='Tổng số bài học của khóa học'),
        ),
    ]
