# Generated by Django 6.0 on 2026-01-03 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0, help_text='Tổng số bài học của khóa học', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
