# Generated by Django 6.0 on 2026-01-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_active_course_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
    ]
