# Generated by Django 6.0 on 2026-01-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('TEACHER', 'Giảng viên'), ('STUDENT', 'Sinh viên')], default='STUDENT', max_length=10),
        ),
    ]
